// Terrain buffer reuse for mod terrain generators, without a mod and without
// touching the other mod's files.
//
// The native toolkit keeps one full-map float buffer per distinct buffer name
// until the pipeline ends (docs/generation-peak.md). The Fantasia Map
// Generator (workshop 2916150031) uses 224 names at 32 x 32 km and 325 at
// 40 km -- MEASURED 53-63 live maps and a std::bad_alloc at 40 km -- and
// mod/generation/bigmap_memory.lua brings every one of its pipelines down to
// 10, the lower bound (tools/test_generator_memory.py).
//
// How: the exe's imports that open files (CreateFileW, _wfopen, fopen and
// std::_Fiopen) are pointed at detours. A read-only open of one of the
// generator files in GENERATORS, in any mod's res\config\terrain_generators, is
// served from a patched copy in %TEMP%\tpf2_bigmap: the one line
// "\t\treturn result" of its updateFn becomes
//     return _tpf2_bigmap_generate(result, params)
// and the pass itself (embedded from bigmap_memory.lua) plus that helper are
// appended after the last line, so every line number in the generator stays
// the same. The helper prints the map size, layer and name counts to the game
// log and runs the pass when the map is over 8193^2 heightmap samples. Maps up to
// 32 x 32 km (128 x 128 tiles) run the generator exactly as shipped. A file
// whose anchor is missing or repeated is served unchanged. The generator on
// disk is never written; switching the plugin off (generator_memory=0) or
// removing it restores stock behaviour on the next start.
//
// Needs ReadWholeFile / WriteWholeFile from bigmap.cpp. Both builds: the
// import slots are found by walking the exe's import directory.
#pragma once
#include "../out/generator_memory_lua.inc"   // kGeneratorMemoryLuaParts[], generated by build.bat

static bool g_generatorMemory = true;

static const wchar_t* const kGeneratorFiles[] = {
    L"fantasia_map_generator.gen.lua",
    L"fantasia_map_generator_dry.gen.lua",
    L"fantasia_map_generator_tropical.gen.lua",
};
static const char kGenAnchor[] = "\t\treturn result";
static const char kGenReplacement[] = "\t\treturn _tpf2_bigmap_generate(result, params) -- tpf2_bigmap memory";
// Appended after the pass: logs what the game handed the generator, then runs
// the pass above 32 x 32 km.
static const char kGenHelper[] = R"BMLUA(
_tpf2_bigmap_generate = function(result, params)
    local x = tonumber(type(params) ~= "nil" and params.mapSizeX) or 0
    local y = tonumber(type(params) ~= "nil" and params.mapSizeY) or 0
    local layers = type(result) == "table" and result.layers
    local n, count, names = 0, 0, {}
    if type(layers) == "table" then
        n = #layers
        for i = 1, n do
            local p = type(layers[i]) == "table" and layers[i].params
            if type(p) == "table" then
                for _, k in ipairs({"input", "input1", "input2", "output"}) do
                    if p[k] ~= nil and not names[p[k]] then names[p[k]] = true; count = count + 1 end
                end
            end
        end
    end
    -- mapSizeX/Y are heightmap samples at 4 m, 64 * tiles + 1 (MEASURED: 12289
    -- for 192 x 192 tiles), so 32 x 32 km (128 x 128 tiles) is 8193 x 8193.
    local big = x * y > 8193 * 8193
    print(string.format("[tpf2_bigmap] generator memory: %.0f x %.0f samples (%.0f x %.0f tiles), %d layers over %d buffer names%s",
        x, y, (x - 1) / 64, (y - 1) / 64, n, count, big and "" or " (32 x 32 km or less: unchanged)"))
    if big then result = _tpf2_bigmap_memory.Optimize(result) end
    return result
end
)BMLUA";

// Index into kGeneratorFiles when `path` is <...>\res\config\terrain_generators\<file>, else -1.
static int GeneratorFileIndex(const wchar_t* path) {
    if (!path) return -1;
    wchar_t low[MAX_PATH * 2];
    size_t n = 0;
    for (; path[n] && n + 1 < _countof(low); ++n) {
        wchar_t c = path[n] == L'/' ? L'\\' : path[n];
        low[n] = (c >= L'A' && c <= L'Z') ? wchar_t(c - L'A' + L'a') : c;
    }
    if (path[n]) return -1;
    low[n] = 0;
    static const wchar_t dir[] = L"\\res\\config\\terrain_generators\\";
    for (int i = 0; i < (int)_countof(kGeneratorFiles); ++i) {
        size_t f = wcslen(kGeneratorFiles[i]), d = _countof(dir) - 1;
        if (n < f + d) continue;
        if (wcscmp(low + n - f, kGeneratorFiles[i]) == 0 && wcsncmp(low + n - f - d, dir, d) == 0) return i;
    }
    return -1;
}

// The patched generator text, malloc'd; nullptr when the anchor is not exactly
// one whole line.
static char* PatchGeneratorText(const char* src, size_t len, size_t* outLen) {
    const size_t a = sizeof kGenAnchor - 1;
    const char* hit = nullptr;
    for (const char* p = src; p + a <= src + len; ++p) {
        if (memcmp(p, kGenAnchor, a) != 0) continue;
        const char* e = p + a;
        bool lineStart = p == src || p[-1] == '\n';
        bool lineEnd = e == src + len || *e == '\n' || (*e == '\r' && e + 1 < src + len && e[1] == '\n');
        if (!lineStart || !lineEnd) continue;
        if (hit) return nullptr;   // repeated
        hit = p;
    }
    if (!hit) return nullptr;
    static const char head[] = "\n_tpf2_bigmap_memory = (function()\n";
    static const char tail[] = "\nend)()\n";
    size_t module = 0;
    for (const char* part : kGeneratorMemoryLuaParts) module += strlen(part);
    const size_t r = sizeof kGenReplacement - 1;
    size_t total = len - a + r + (sizeof head - 1) + module + (sizeof tail - 1) + (sizeof kGenHelper - 1);
    char* out = (char*)malloc(total + 1);
    if (!out) return nullptr;
    char* o = out;
    size_t pre = size_t(hit - src);
    memcpy(o, src, pre); o += pre;
    memcpy(o, kGenReplacement, r); o += r;
    memcpy(o, hit + a, len - pre - a); o += len - pre - a;
    memcpy(o, head, sizeof head - 1); o += sizeof head - 1;
    for (const char* part : kGeneratorMemoryLuaParts) { size_t k = strlen(part); memcpy(o, part, k); o += k; }
    memcpy(o, tail, sizeof tail - 1); o += sizeof tail - 1;
    memcpy(o, kGenHelper, sizeof kGenHelper - 1); o += sizeof kGenHelper - 1;
    *o = 0;
    *outLen = size_t(o - out);
    return out;
}

static SRWLOCK g_genLock = SRWLOCK_INIT;
static volatile LONG g_genServed[_countof(kGeneratorFiles)];

// The patched copy of `path` in %TEMP%\tpf2_bigmap, written when it differs.
// False (serve the original) on any failure.
static bool GeneratorRedirect(const wchar_t* path, wchar_t* out, size_t cch) {
    int i = GeneratorFileIndex(path);
    if (i < 0 || !g_generatorMemory) return false;
    wchar_t dir[MAX_PATH];
    DWORD t = GetTempPathW(MAX_PATH, dir);
    if (!t || t >= MAX_PATH) return false;
    if (_snwprintf_s(out, cch, _TRUNCATE, L"%stpf2_bigmap", dir) < 0) return false;
    CreateDirectoryW(out, nullptr);
    if (_snwprintf_s(out, cch, _TRUNCATE, L"%stpf2_bigmap\\%s", dir, kGeneratorFiles[i]) < 0) return false;

    AcquireSRWLockExclusive(&g_genLock);
    bool ok = false;
    char *src = nullptr, *cur = nullptr, *patched = nullptr;
    size_t srcLen = 0, curLen = 0, patchedLen = 0;
    if (ReadWholeFile(path, &src, &srcLen) && (patched = PatchGeneratorText(src, srcLen, &patchedLen))) {
        bool same = ReadWholeFile(out, &cur, &curLen) && curLen == patchedLen && memcmp(cur, patched, curLen) == 0;
        ok = same || WriteWholeFile(out, patched, patchedLen);
    }
    ReleaseSRWLockExclusive(&g_genLock);
    if (H && InterlockedExchange(&g_genServed[i], 1) == 0) {
        if (ok) H->log("generator memory: %ls served with buffer reuse above 32 x 32 km (%ls)", kGeneratorFiles[i], out);
        else H->log("generator memory: %ls served unchanged (%s)", kGeneratorFiles[i],
                    src ? "its 'return result' line is missing or repeated" : "unreadable");
    }
    free(src); free(cur); free(patched);
    return ok;
}

// ---- import detours --------------------------------------------------------
using CreateFileWFn = HANDLE(WINAPI*)(LPCWSTR, DWORD, DWORD, LPSECURITY_ATTRIBUTES, DWORD, DWORD, HANDLE);
using WfopenFn = FILE*(__cdecl*)(const wchar_t*, const wchar_t*);
using FopenFn = FILE*(__cdecl*)(const char*, const char*);
using FiopenFn = FILE*(__cdecl*)(const wchar_t*, int, int);
static CreateFileWFn g_origCreateFileW;
static WfopenFn g_origWfopen;
static FopenFn g_origFopen;
static FiopenFn g_origFiopen;

static HANDLE WINAPI GenCreateFileW(LPCWSTR path, DWORD access, DWORD share, LPSECURITY_ATTRIBUTES sa,
                                    DWORD disposition, DWORD flags, HANDLE tmpl) {
    wchar_t alt[MAX_PATH];
    if (!(access & (GENERIC_WRITE | GENERIC_ALL | FILE_WRITE_DATA | FILE_APPEND_DATA | DELETE)) &&
        disposition == OPEN_EXISTING && GeneratorRedirect(path, alt, MAX_PATH))
        path = alt;
    return g_origCreateFileW(path, access, share, sa, disposition, flags, tmpl);
}
static bool ReadOnlyMode(const wchar_t* m) { return m && !wcspbrk(m, L"wa+"); }
static FILE* __cdecl GenWfopen(const wchar_t* path, const wchar_t* mode) {
    wchar_t alt[MAX_PATH];
    if (ReadOnlyMode(mode) && GeneratorRedirect(path, alt, MAX_PATH)) path = alt;
    return g_origWfopen(path, mode);
}
static FILE* __cdecl GenFopen(const char* path, const char* mode) {
    if (path && mode && !strpbrk(mode, "wa+")) {
        // The narrow path is UTF-8 or the ANSI code page; answer in the one that decoded it.
        const UINT pages[] = {CP_UTF8, CP_ACP};
        for (UINT cp : pages) {
            wchar_t wide[MAX_PATH], alt[MAX_PATH];
            if (!MultiByteToWideChar(cp, cp == CP_UTF8 ? MB_ERR_INVALID_CHARS : 0, path, -1, wide, MAX_PATH)) continue;
            if (GeneratorFileIndex(wide) < 0) return g_origFopen(path, mode);
            char narrow[MAX_PATH * 3];
            BOOL lossy = FALSE;
            if (GeneratorRedirect(wide, alt, MAX_PATH) &&
                WideCharToMultiByte(cp, 0, alt, -1, narrow, sizeof narrow, nullptr, cp == CP_UTF8 ? nullptr : &lossy) && !lossy)
                return g_origFopen(narrow, mode);
            break;
        }
    }
    return g_origFopen(path, mode);
}
static FILE* __cdecl GenFiopen(const wchar_t* path, int mode, int prot) {
    // std::ios_base: out 0x02, app 0x08, trunc 0x10.
    wchar_t alt[MAX_PATH];
    if (!(mode & (0x02 | 0x08 | 0x10)) && GeneratorRedirect(path, alt, MAX_PATH)) path = alt;
    return g_origFiopen(path, mode, prot);
}

// RVA of the import slot for dll!name in the exe, 0 when it is not imported by name.
static uintptr_t ImportSlotRva(uintptr_t base, const char* dll, const char* name) {
    auto dos = reinterpret_cast<const IMAGE_DOS_HEADER*>(base);
    auto nt = reinterpret_cast<const IMAGE_NT_HEADERS64*>(base + dos->e_lfanew);
    const IMAGE_DATA_DIRECTORY& dirEntry = nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];
    if (!dirEntry.VirtualAddress) return 0;
    for (auto d = reinterpret_cast<const IMAGE_IMPORT_DESCRIPTOR*>(base + dirEntry.VirtualAddress); d->Name; ++d) {
        if (_stricmp(reinterpret_cast<const char*>(base + d->Name), dll) != 0 || !d->OriginalFirstThunk) continue;
        auto names = reinterpret_cast<const IMAGE_THUNK_DATA64*>(base + d->OriginalFirstThunk);
        for (size_t k = 0; names[k].u1.AddressOfData; ++k) {
            if (IMAGE_SNAP_BY_ORDINAL64(names[k].u1.Ordinal)) continue;
            auto byName = reinterpret_cast<const IMAGE_IMPORT_BY_NAME*>(base + names[k].u1.AddressOfData);
            if (strcmp(reinterpret_cast<const char*>(byName->Name), name) == 0)
                return d->FirstThunk + k * sizeof(IMAGE_THUNK_DATA64);
        }
    }
    return 0;
}

static bool RouteImport(const char* dll, const char* name, void* detour, void** original) {
    uintptr_t base = H->moduleBase();
    uintptr_t rva = ImportSlotRva(base, dll, name);
    if (!rva) { H->log("generator memory: %s!%s is not imported; that open path is not watched", dll, name); return false; }
    *original = *reinterpret_cast<void**>(base + rva);
    uint8_t bytes[8]; memcpy(bytes, &detour, 8);
    if (!H->patchBytes(rva, bytes, 8)) { H->log("generator memory: %s!%s import patch failed", dll, name); return false; }
    return true;
}

static bool InstallGeneratorMemory() {
    if (!g_generatorMemory) { H->log("generator memory: off (generator_memory=0)"); return false; }
    int routed = 0;
    routed += RouteImport("KERNEL32.dll", "CreateFileW", (void*)GenCreateFileW, (void**)&g_origCreateFileW);
    routed += RouteImport("api-ms-win-crt-stdio-l1-1-0.dll", "_wfopen", (void*)GenWfopen, (void**)&g_origWfopen);
    routed += RouteImport("api-ms-win-crt-stdio-l1-1-0.dll", "fopen", (void*)GenFopen, (void**)&g_origFopen);
    routed += RouteImport("MSVCP140.dll", "?_Fiopen@std@@YAPEAU_iobuf@@PEB_WHH@Z", (void*)GenFiopen, (void**)&g_origFiopen);
    if (!routed) { H->log("generator memory: no file-open import could be watched; OFF"); return false; }
    H->log("generator memory: Fantasia Map Generator files get buffer reuse above 32 x 32 km (%d of 4 open paths watched; the files on disk are not changed)", routed);
    return true;
}

extern "C" __declspec(dllexport) int BigmapTestGeneratorRedirect(const wchar_t* path, wchar_t* out, size_t cch) { return GeneratorRedirect(path, out, cch); }
extern "C" __declspec(dllexport) int BigmapTestGeneratorIndex(const wchar_t* path) { return GeneratorFileIndex(path); }
extern "C" __declspec(dllexport) long long BigmapTestGeneratorPatch(const char* src, size_t len, char* out, size_t cap) {
    size_t n = 0;
    char* p = PatchGeneratorText(src, len, &n);
    if (!p) return -1;
    long long r = (long long)n;
    if (n <= cap) memcpy(out, p, n);
    free(p);
    return r;
}
